name: NodeJS Build CI
run-name: ${{ github.actor }} is building tinbug.cool with GH actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v
      
      - name: Run a one-line script
        run: echo Running builder...

      - name: Run a multi-line script
        run: npx vite build
        
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://tinbug.cool --delete
